# Minumum Version
CMAKE_MINIMUM_REQUIRED(VERSION 2.8.5)

# Set CMake Module Path
SET(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} ${CMAKE_CURRENT_SOURCE_DIR}/cMake)

# Include Macros
Include(Macros)

# Get Information
COMMAND_TO_CONFIGVAR(whoami USER)
STRING(STRIP ${USER} USER)
STRING(REPLACE "\\" "\\\\" USER ${USER})
FILE(READ version_liggghts.txt LIGGHTS_VERSION)
STRING(STRIP ${LIGGHTS_VERSION} LIGGHTS_VERSION)
FILE(READ version_liggghts_branch.txt LIGGHTS_BRANCH)
STRING(STRIP ${LIGGHTS_BRANCH} LIGGHTS_BRANCH)
GETDATETIME(BUILDDATE "%Y-%m-%d %H:%M:%S")
CONFIGURE_FILE(${CMAKE_CURRENT_SOURCE_DIR}/version_liggghts.in ${CMAKE_CURRENT_SOURCE_DIR}/version_liggghts.h)
